# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-10 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodpantry', '0004_auto_20181109_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=10)),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donorname', models.CharField(max_length=50)),
                ('joindate', models.DateField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=100)),
                ('notes', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='createddate',
            new_name='createdate',
        ),
        migrations.AddField(
            model_name='donation',
            name='donar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foodpantry.Donor'),
        ),
        migrations.AddField(
            model_name='donation',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foodpantry.Inventory'),
        ),
    ]
