# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-13 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodpantry', '0005_auto_20181110_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='donar',
            new_name='donor',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='received_date',
            new_name='receiveddate',
        ),
    ]
