# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-27 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodpantry', '0006_auto_20181112_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='receiveddate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='donor',
            name='joindate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set([]),
        ),
    ]
