# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-06 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodpantry', '0010_auto_20181206_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='foodpantry.Inventory'),
        ),
    ]
