# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-10 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodpantry', '0011_auto_20181206_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='receiveddate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='joindate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
