# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-11 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodpantry', '0012_auto_20181209_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='receiveddate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
