# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-13 16:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodpantry', '0013_auto_20181211_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='itemname',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='cellphone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volnotes',
            field=models.CharField(max_length=500),
        ),
    ]
